# Generated by Django 3.1.4 on 2021-04-27 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_blogmodel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.blogmodel')),
                ('usr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.userdetail')),
            ],
        ),
        migrations.CreateModel(
            name='CommentBLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.blogmodel')),
                ('usr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.userdetail')),
            ],
        ),
    ]
