# Generated by Django 3.1.4 on 2021-04-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_commentblog_likeblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentblog',
            name='commentdate',
            field=models.DateField(null=True),
        ),
    ]
